
 
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('가나다','냐냥', '라라');
 
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('라마바','냐냥', '라라');
 
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('사아자','냐냥', '라라');
 
COMMIT;
 
SELECT * FROM BOARD;